query Heros($herosSkip: Int!, $herosTake: Int!){
  heros(skip: $herosSkip, take: $herosTake) {
    id
    createdAt
    updatedAt
    nickname
    real_name
    origin_description
    superpowers
    catch_phrase
    images {
      id
      name
    }
  }
}